### ISSUE TITLE
生成错误

### ISSUE THREAD

**Issue by ZHENGX1N** [feynmandj/MuseGPT-Page#1]
抱歉,生成摘要时发生请求错误,请尝试重试
status:429

**Comment by augusdin** [comment]
@ZHENGX1N 

你好，按照现有经验来看，报错429通常是因为你填入的api key 的免费额度用完、免费额度过期(openai为新账户赠送的5$免费额度是有三个月期限的)，以及api因为没有续费而没有使用额度了。
<img width="1013" alt="2023-08-03_13 17 25" src="https://github.com/feynmandj/MuseGPT-Page/assets/129820382/c562580b-1be3-429b-8446-50a584508af8">
请访问链接
https://platform.openai.com/account/usage
并登录，查看自己的Usage部分，如果没有问题，请截图给我，谢谢
